import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { InlineCallout, PageIntro, RelatedLinks, SourceList } from "@/components/PageParts";
import { ROBLOX_URL, pageMetadata } from "@/lib/site";

export const metadata: Metadata = pageMetadata({ title: "About the Unbox ASMR Roblox Guide", description: "About this independent Unbox ASMR Roblox player guide, its evidence policy, ownership notice, and correction approach.", path: "/about/" });

export default function About() {
  return <div className="container page-shell"><Breadcrumbs items={[{ label: "About", href: "/about/" }]}/><PageIntro eyebrow="Independent by design" title="About the Unbox ASMR Guide" description="A fan-made answer desk and data guide for the Roblox experience developed by ASMR Labs—not an official wiki, shop, or Roblox service."/><div className="narrow prose"><InlineCallout title="Independence notice"><p>This site is not affiliated with Roblox Corporation or ASMR Labs. It does not sell Robux, Gamepasses, codes, accounts, or access to the game.</p></InlineCallout><h2>Why this guide exists</h2><p>New game searches often fill with copied descriptions, invented codes, and values without dates. This guide takes the slower, more useful route: give the direct answer first, attach an evidence state and date, and leave a field empty when it cannot be proved.</p><h2>What “verified” means here</h2><p>Facts are labeled Official, In-game verified, Community reported, or Unverified. In-game evidence outranks an older community list. A price snapshot does not become a value recommendation, and rarity does not become an earnings claim.</p><h2>Corrections</h2><p>No public comments or personal-data form is included in the MVP. Corrections should be supported by a current official URL or a privacy-cropped gameplay capture. A compliant contact channel can be added later.</p><h2>Rights and ownership</h2><p>Roblox and the game’s names and assets belong to their respective owners. Screenshots, when added, will be used only to explain gameplay and will remove usernames, chat, and unrelated personal information.</p><p><a className="button button-secondary" href={ROBLOX_URL} target="_blank" rel="noopener noreferrer">Visit the official Roblox experience ↗</a></p><RelatedLinks links={[{ href: "/sources/", label: "Sources & methodology" }, { href: "/privacy/", label: "Privacy" }, { href: "/terms/", label: "Terms" }]}/><SourceList sources={[{ label: "Official Unbox ASMR Roblox experience", url: ROBLOX_URL }, { label: "Official ASMR Labs Roblox group", url: "https://www.roblox.com/communities/1110056661/ASMR-Labs" }]}/></div></div>;
}
