import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { PageIntro, RelatedLinks } from "@/components/PageParts";
import { pageMetadata } from "@/lib/site";

export const metadata: Metadata = pageMetadata({ title: "Privacy", description: "Privacy approach for the Unbox ASMR Guide: no accounts, profiles, comments, or personal gameplay data collection in the MVP.", path: "/privacy/" });

export default function Privacy() {
  return <div className="container page-shell"><Breadcrumbs items={[{ label: "Privacy", href: "/privacy/" }]}/><PageIntro eyebrow="Plain-language policy" title="Privacy" description="This guide answers game questions without requiring an account or collecting Roblox login credentials."/><article className="narrow prose"><h2>What the site does not ask for</h2><ul><li>No Roblox username, password, or account credentials.</li><li>No age, minor-status, profile, comments, or saved cloud progress.</li><li>No site account, login, or payment information.</li></ul><h2>Microsoft Clarity usage analytics</h2><p>This site uses Microsoft Clarity to understand aggregate page usage and interaction patterns such as navigation, clicks, taps, and scrolling. Clarity can provide heatmaps and reconstructed session recordings so broken interactions and confusing pages can be improved.</p><p>Microsoft may process browser, device, page, and interaction data and may use cookies or similar technologies according to applicable consent rules. Review the <a href="https://clarity.microsoft.com/privacy" target="_blank" rel="noopener noreferrer">Microsoft Clarity privacy information</a> for provider details.</p><h2>Basic usage events</h2><p>The interface also records broad event names such as using a table filter or following the official Roblox link. These events do not intentionally contain Roblox usernames, account credentials, or form text.</p><h2>External links</h2><p>Roblox and source websites have their own privacy practices. External links open directly to those providers and are clearly labeled.</p><h2>Gameplay evidence</h2><p>Any future screenshots must crop usernames, chat, and unrelated personal information before being stored in the project.</p><p className="muted">Last reviewed: August 4, 2026.</p><RelatedLinks links={[{ href: "/about/", label: "About" }, { href: "/terms/", label: "Terms" }]}/></article></div>;
}
