import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { PageIntro, RelatedLinks, SourceList } from "@/components/PageParts";
import { VerificationBadge } from "@/components/Verification";
import { pageMetadata } from "@/lib/site";

export const metadata: Metadata = pageMetadata({ title: "Unbox ASMR Sources and Verification Method", description: "How the Unbox ASMR Roblox guide ranks sources, dates evidence, handles missing data, and prevents fabricated claims.", path: "/sources/" });

export default function Sources() {
  return <div className="container page-shell"><Breadcrumbs items={[{ label: "Sources", href: "/sources/" }]}/><PageIntro eyebrow="Trust is visible" title="Sources and Verification Method" description="Every decision-changing fact needs a status, a specific date, and a retrievable source. Missing evidence is shown as missing—not smoothed over."/><div className="narrow prose"><h2>Evidence states</h2><div className="ordered-cards"><div className="info-card"><VerificationBadge status="official"/><h3>Official</h3><p>Roblox experience pages, the ASMR Labs group, or an official event announcement.</p></div><div className="info-card"><VerificationBadge status="in_game_verified"/><h3>In-game verified</h3><p>A current-version, privacy-cropped screenshot or recording that proves the displayed claim.</p></div><div className="info-card"><VerificationBadge status="community_reported"/><h3>Community reported</h3><p>A dated public source that is useful context but not treated as absolute truth.</p></div><div className="info-card"><VerificationBadge status="unverified"/><h3>Unverified</h3><p>Not eligible for rankings, calculators, recommendations, or confident instructions.</p></div></div><h2>Source priority</h2><ol><li>Current-version in-game screenshot or recording.</li><li>Official Roblox experience page or event surface.</li><li>Official ASMR Labs group or announcement.</li><li>Roblox public data or a dated Rolimon’s snapshot.</li><li>Credible media reporting.</li><li>Video or community reports with retrievable context.</li></ol><h2>Freshness rules</h2><ul><li>Show an exact checked or verified date—never “updated recently” or “updated daily.”</li><li>Re-check events, codes, prices, and changed game systems after every update.</li><li>Do not let a later-priority source override newer in-game proof.</li><li>Remove thin, incomplete data pages from the sitemap until they become useful.</li></ul><h2>Build-time gates</h2><p>The build rejects duplicate slugs, invalid event windows, unsupported active codes, verdicts on wholly unverified Gamepasses, and toy references to missing crates.</p><RelatedLinks links={[{ href: "/about/", label: "About" }, { href: "/updates/", label: "Updates" }, { href: "/codes/", label: "Codes" }]}/><SourceList sources={[{ label: "Official Unbox ASMR Roblox experience", url: "https://www.roblox.com/games/112233638491976/Unbox-ASMR" }, { label: "Official ASMR Labs Roblox group", url: "https://www.roblox.com/communities/1110056661/ASMR-Labs" }, { label: "Rolimon’s public game page", url: "https://www.rolimons.com/game/112233638491976" }, { label: "All Things How event schedule", url: "https://allthings.how/unbox-asmr-events-schedule/" }, { label: "Beebom codes report", url: "https://beebom.com/unbox-asmr-codes/" }]}/></div></div>;
}
