import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { DataTable } from "@/components/DataTable";
import { InlineCallout, PageIntro, RelatedLinks, SourceList } from "@/components/PageParts";
import { MissingValue, VerificationBadge } from "@/components/Verification";
import { gamepasses } from "@/lib/data";
import { pageMetadata, ROBLOX_URL } from "@/lib/site";

export const metadata: Metadata = pageMetadata({ title: "Unbox ASMR Gamepasses — Prices & Verified Effects", description: "Dated Unbox ASMR Gamepass price snapshots for Roblox, with effects and value verdicts withheld until in-game verification.", path: "/gamepasses/" });

export default function Gamepasses() {
  const rows = gamepasses.map((pass) => [pass.name, <span className="numeric" key="price">{pass.priceRobux} Robux</span>, <MissingValue key="effect"/>, <MissingValue key="best"/>, <MissingValue key="stage"/>, <MissingValue key="verdict"/>, <VerificationBadge key="badge" status={pass.evidence[0].status}/>, "Jul 30, 2026"]);
  return <div className="container page-shell"><Breadcrumbs items={[{ label: "Gamepasses", href: "/gamepasses/" }]}/><PageIntro eyebrow="Spend with context" title="Unbox ASMR Gamepass Price and Effect Tracker" description="Seven public prices are recorded as a dated third-party snapshot. No pass earns a “best” label until its in-game effect and player value are actually tested."/><InlineCallout title="Direct answer"><p>There is not enough current in-game evidence to name a best Unbox ASMR Gamepass. Price does not prove effect, usefulness, or return on Robux. Free-to-play players can wait for verified descriptions before buying.</p></InlineCallout><section className="section-compact"><div className="desktop-gamepass-table"><DataTable label="Unbox ASMR Gamepass comparison" headers={["Name","Public price","Verified effect","Best for","Stage","Value verdict","Evidence","Checked"]} rows={rows}/></div><div className="mobile-card-table">{gamepasses.map((pass) => <article className="mobile-data-card" key={pass.slug}><h3>{pass.name}</h3><dl><dt>Public price</dt><dd>{pass.priceRobux} Robux</dd><dt>Effect</dt><dd><MissingValue/></dd><dt>Value verdict</dt><dd><MissingValue/></dd><dt>Evidence</dt><dd><VerificationBadge status={pass.evidence[0].status}/></dd><dt>Checked</dt><dd>Jul 30, 2026</dd></dl></article>)}</div></section><section className="split-cards"><article className="info-card"><h2>For free-to-play players</h2><p>You do not need a Gamepass to use this guide. Wait until the exact effect, stage fit, and any limitations are visible in the current game UI.</p></article><article className="info-card warm-panel"><h2>What we still need</h2><p>Each in-game description, the official purchase surface, a before/after test where safe, and the current price. Only then can a dated verdict be considered.</p></article></section><section className="section-compact narrow"><h2>Price snapshot timeline</h2><ol className="ordered-cards"><li><strong>July 30, 2026 · Public snapshot</strong> Rolimon’s listed seven passes from 11 to 499 Robux. This records price only; it does not verify the effect or value.</li></ol><p className="muted">Prices and effects can change after an update. This site does not sell Robux or Gamepasses.</p><div style={{height:20}}/><a className="button button-secondary" href={ROBLOX_URL} target="_blank" rel="noopener noreferrer" data-event="gamepass_official_click">View the official experience on Roblox ↗</a></section><RelatedLinks links={[{ href: "/beginner-guide/", label: "Beginner Guide" }, { href: "/rebirths-and-workers/", label: "Rebirths & Workers" }]}/><SourceList sources={[{ label: "Rolimon’s Unbox ASMR public page", url: "https://www.rolimons.com/game/112233638491976", note: "Community-reported price snapshot checked July 30, 2026." }, { label: "Official Unbox ASMR Roblox experience", url: ROBLOX_URL, note: "Use Roblox as the purchase authority; re-check live before spending." }]}/></div>;
}
