import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { EventCountdown } from "@/components/EventCountdown";
import { InlineCallout, PageIntro, RelatedLinks, SourceList } from "@/components/PageParts";
import { VerificationBadge } from "@/components/Verification";
import { events, changelog } from "@/lib/data";
import { pageMetadata } from "@/lib/site";

export const metadata: Metadata = pageMetadata({ title: "Unbox ASMR Update 3 & Admin Abuse Time", description: "The reported Unbox ASMR Update 3 and Admin Abuse schedule with ET, PT, local time, evidence status, and no guessed features.", path: "/updates/" });

export default function Updates() {
  const event = events[0];
  return <div className="container page-shell"><Breadcrumbs items={[{ label: "Updates", href: "/updates/" }]}/><PageIntro eyebrow="Event desk" title="Unbox ASMR Update 3 and Admin Abuse" description="The schedule below is community-reported, dated, and shown with a local-time conversion. Specific update contents remain unconfirmed until official or in-game evidence arrives."/><div className="event-banner"><div className="event-banner-copy"><VerificationBadge status="community_reported"/><h2>{event.name}</h2><p>Starts Aug 2, 2026 · 3:00 PM ET / 12:00 PM PT<br/>Ends Aug 9, 2026 · 3:00 PM ET / 12:00 PM PT</p></div><EventCountdown startsAt={event.startsAt} endsAt={event.endsAt} initialStatus={event.publishedStatus}/></div><section className="section-compact split-cards"><article className="info-card keep-card"><h2>Confirmed in the published schedule</h2><ul>{event.confirmedChanges.map((item) => <li key={item}>{item}</li>)}</ul></article><article className="info-card"><h2>Not announced or verified</h2><ul>{event.unconfirmedNotes.map((item) => <li key={item}>{item}</li>)}</ul></article></section><InlineCallout title="Preview versus implementation" tone="reported"><p>A schedule is not a changelog. After the event begins, preview claims and the features actually visible in-game must be listed separately. Codes, crates, toys, rebirths, and Gamepasses all need a fresh check.</p></InlineCallout><section className="section-compact narrow"><h2>Changelog</h2><ol className="ordered-cards">{changelog.map((item) => <li key={item.date}><strong>{item.date} · {item.title}</strong>{item.details}</li>)}</ol></section><section className="summary-card warm-panel"><h2>Post-update verification queue</h2><p>Capture the event panel, official announcement, new or changed crate/toy panels, rebirth confirmation, Gamepass descriptions, and any code redemption result. Update the evidence date on every affected page.</p></section><RelatedLinks links={[{ href: "/codes/", label: "Codes status" }, { href: "/crates-and-toys/", label: "Crates & Toys" }, { href: "/sources/", label: "Evidence policy" }]}/><SourceList sources={[{ label: "All Things How event schedule", url: "https://allthings.how/unbox-asmr-events-schedule/", note: "Community-reported schedule checked July 30, 2026; re-check against official channels before launch." }, { label: "Official Unbox ASMR Roblox experience", url: "https://www.roblox.com/games/112233638491976/Unbox-ASMR" }]}/></div>;
}
